sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jungyinl/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jungyinl/complex npm run test -- --coverage
 
after_success:
  - docker build -t jungyinl/multi-client ./client
  - docker build -t jungyinl/multi-nginx ./nginx
  - docker build -t jungyinl/multi-server ./server
  - docker build -t jungyinl/multi-worker ./worker
# log in to the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker
  