sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jungyinl/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jungyinl/complex npm run test -- --coverage
 
 after_success:
  - docker build -t jungyinl/multi-client ./client
  - docker build -t jungyinl/multi-nginx ./nginx
  - docker build -t jungyinl/multi-server ./server
  - docker build -t jungyinl/multi-worker ./worker